name: Push Buzzer

on:
  push:

permissions: 
  contents: write

jobs:
  Registro-mensajes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: escribir en el README
        run: |
          echo -e "\n\nUltimo mensajes registrado Hacia el arduino:  $(date)" >> README.md

      - name: configurancion git en el servidor
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: hacer commit y push en el servior
        run: |
          git add README.md
          git commit -m "Update README automatically"
          git push
      
  envio-mensajes:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar cliente Mosquitto
        run: sudo apt-get update && sudo apt-get install -y mosquitto-clients

      - name: Publicar en MQTT
        run: mosquitto_pub -h test.mosquitto.org -p 1883 -t "GiuhubToHeltec" -m "Hola desde GitHub Actions"